#ifndef TESTS_H
#define TESTS_H

#include <future>
#include <iostream>
#include <string>
#include <vector>

#include <web3cpp/Web3.h>

/**
 * Helper class for unit testing.
 * Each test should be completely contained into a function of its own.
 */

class Tests {
  private:
    // The Web3 object that will be tested
    Web3 web3;
    std::string password;

    // Counters for passed/failed tests, and functions for controlling those
    int pass = 0;
    int fail = 0;
    void passed() {
      std::cout << "* PASSED" << std::endl;
      pass++;
    }
    void failed(std::string msg) {
      std::cout << "* FAILED - " << msg << std::endl;
      fail++;
    }

  public:
    // Constructor
    // TODO: custom path for test wallet
    Tests(std::string &password) {
      Error error;
      std::cout << "Creating/Loading wallet..." << std::endl;
      if (!web3.wallet.loadWallet(password, error)) {
        std::cout << std::string("Could not load wallet: ") << error.what() << std::endl;
        throw;
      }
      this->password = password;
      std::cout << "Wallet created/loaded, starting tests" << std::endl
        << "----------------------------------------" << std::endl;
    }

    // Show overall test results
    void showResults() {
      std::cout << "----------------------------------------\n"
        << "* RESULTS: " << pass << " passed, " << fail << " failed\n"
        << "----------------------------------------\n";
    }

    // TODO: test for valid seedphrase

    /**
     * Test for valid Account generation.
     * Required inputs:
     * - A derivation path
     * - A seedphrase to use for generating the address
     * - A name for the Account
     * - An example address generated by said seedphrase for comparison
     * Fails in the following conditions:
     * - TODO: derivPath is not valid
     * - TODO: seed is not valid
     * - TODO: name is not valid
     * - TODO: example is not valid
     * - Account is not properly created
     * - Account created doesn't match the example
     */
    void generateAccount(
      std::string derivPath, std::string seed, std::string name, std::string example
    ) {
      Error error;
      std::cout << "* Running test: " << __func__ << std::endl
        << "* Derivation path: " << derivPath << std::endl
        << "* Seed: " << seed << std::endl
        << "* Name: " << name << std::endl
        << "* Example: " << example << std::endl;
      std::string result = web3.wallet.createNewAccount(
        derivPath, this->password, name, error, seed
      );
      if (result.empty()) {
        failed(std::string("Could not create account: ") + error.what()); return;
      }
      if (result != Utils::toChecksumAddress(example)) {
        failed("Accounts don't match");
        std::cout << "Expected output: " << example << std::endl;
        std::cout << "Actual output: " << result << std::endl;
        return;
      }
      passed(); return;
    }
};

#endif // TESTS_H
